version: '3'
services:
  db:
    image: mysql:8.0
    env_file: ./.env
    ports:
      - '4306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local