version: '3.7'

services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: '2.7.1'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.4'
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/self-management-app
      - public-data:/self-management-app/public
      - tmp-data:/self-management-app/tmp
      - log-data:/self-management-app/log
    # depends_on:
    #   - db
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: self-management-app_db
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "4306:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/self-management-app/public
      - tmp-data:/self-management-app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  # mysql-data: