version: '3'
services:
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_DATABASE: self-management-app_db
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/self-management-app
      - public-data:/self-management-app/public
      - tmp-data:/self-management-app/tmp
      - log-data:/self-management-app/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/self-management-app/public
      - tmp-data:/self-management-app/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data:
  # chrome:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - 4444:4444
  #   stdin_open: true
  #   tty: true